server:
  port: 8088


spring:
  application:
    name: ecom_platform
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-791k7o65.sql.tencentcdb.com:26579/ecom_platform?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 18428149886waNG
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Swagger 3.0与Spring Boot的兼容性问题
  mail:
    host: smtp.qq.com
    username: 1369281736@qq.com
    password: hyjzsnhrtdsiicai
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

# Swagger配置
swagger:
  enable: true  # 是否启用Swagger，生产环境可设为false

# MyBatis-Plus配置  
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.db.ecom_platform.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true

# 阿里云短信服务配置
aliyun:
  sms:
    access-key-id:
    access-key-secret:
    sign-name: 阿里云短信测试
    template-code: SMS_154950909  # 验证码模板编码

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: ecomPlatformSecretKey
  # JWT的过期时间（毫秒），这里设置24小时
  expiration: 86400000
