server:
  port: 8088


spring:
  application:
    name: ecom_platform
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-791k7o65.sql.tencentcdb.com:26579/ecom_platform?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 18428149886waNG
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Swagger 3.0与Spring Boot的兼容性问题

# Swagger配置
swagger:
  enable: true  # 是否启用Swagger，生产环境可设为false

# MyBatis-Plus配置  
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.db.ecom_platform.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true


